### ISSUE TITLE
```FundMe``` "constructor" taking arguments  #bug

### ISSUE THREAD

**Issue by khandelwalmoksh** [Cyfrin/foundry-fund-me-cu#85]
Original taking arguments: ```constructor(address priceFeed) {
        s_priceFeed = AggregatorV3Interface(priceFeed);
        i_owner = msg.sender;
    }```
    Error " Wrong argument count for function call: 0 arguments given but expected 1. --> test/FundMeTest.t.sol:10:14:"
    
    It should be:
    ```constructor() {
        i_owner = msg.sender;
    }```
    
  link to code :  https://github.com/Cyfrin/foundry-fund-me-cu/blob/main/src/FundMe.sol
 For reference, link to issue: https://github.com/Cyfrin/foundry-full-course-cu/discussions/2687

**Comment by khandelwalmoksh** [comment]
Original taking arguments:

```constructor(address priceFeed) {
        s_priceFeed = AggregatorV3Interface(priceFeed);
        i_owner = msg.sender;
    }```

**Comment by EngrPips** [comment]
Hello @khandelwalmoksh, I understand your suggestion, but this is not an issue with the codebase as the code will still change if you continue taking the course, and you will get to the point where the `constructor` will take an argument so that the address of price feed contract is not fixed but instead passed into the contract at deployment.
